import "@rainbow-me/rainbowkit/styles.css";
import "../styles/globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "RainbowKit App",
  description: "Generated by @rainbow-me/create-rainbowkit",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link href="/favicon.ico" rel="icon" />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
